e-commerce-symfony/src/Entity/Commentaire.php
<?php

namespace App\Entity;

use App\Repository\CommentaireRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommentaireRepository::class)
 */
class Commentaire
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="commentaire")
     * @ORM\JoinColumn(nullable=false)
     */
    private $users;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_produit;

    /**
     * @ORM\Column(type="text")
     */
    private $commentaire;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdProduit(): ?int
    {
        return $this->id_produit;
    }

    public function setIdProduit(int $id_produit): self
    {
        $this->id_produit = $id_produit;

        return $this;
    }

    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    public function setCommentaire(string $commentaire): self
    {
        $this->commentaire = $commentaire;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getUsers(): ?Users
    {
        return $this->users;
    }

    public function setUsers(?Users $users): self
    {
        $this->users = $users;

        return $this;
    }
}

e-commerce-symfony/src/Form/CommentaireType.php
<?php

namespace App\Form;

use App\Entity\Commentaire;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommentaireType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('id_produit')
            ->add('commentaire')
            ->add('date')
            ->add('users')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Commentaire::class,
        ]);
    }
}

e-commerce-symfony/src/Controller/CommentaireController.php
<?php

namespace App\Controller;

use Firebase\JWT\JWT;
use App\Entity\Commentaire;
use App\Form\CommentaireType;
use App\Repository\UsersRepository;
use App\Repository\CommentaireRepository;
use Symfony\Component\Serializer\Serializer;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Serializer\Encoder\XmlEncoder;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Normalizer\AbstractNormalizer;
use Symfony\Component\Serializer\Normalizer\DateTimeNormalizer;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\DependencyInjection\ParameterBag\ContainerBagInterface;

/**
 * @Route("/commentaire")
 */
class CommentaireController extends AbstractController
{
    public function __construct(ContainerBagInterface $params)
    {
        $this->encoders = [new XmlEncoder(), new JsonEncoder()];
        $defaultContext = [
            AbstractNormalizer::CIRCULAR_REFERENCE_HANDLER => function ($object, $format, $context) {
                return $object->getId();
            },
        ];
        $this->normalizers = [new DateTimeNormalizer(), new ObjectNormalizer(null, null, null, null, null, null, $defaultContext)];
        $this->serializer = new Serializer($this->normalizers, $this->encoders);
        $this->params = $params;
    }

    /**
     * @Route("/new", name="commentaire_new", methods={"POST"})
     */
    public function new(Request $request, UsersRepository $usersRepository): Response
    {
        if (strlen(trim($request->get("comment"))) === 0 ) {
            return new JsonResponse(["Status" => "Error", "Msg" => "No comment"], Response::HTTP_ACCEPTED);
        }
        $em = $this->getDoctrine()->getManager();

        $credentials = $request->headers->get("Authorization");
        $jwt = (array) JWT::decode(
            $credentials,
            $this->params->get('jwt_secret'),
            ['HS256']
        );
        $user = $usersRepository->findOneBy(["email" => $jwt["user"]]);

        $comment = new Commentaire();
        $comment->setIdProduit(intval($request->get("id_produit")));
        $comment->setUsers($user);
        $comment->setCommentaire($request->get("comment"));
        $now = new \DateTime();
        $now->format('Y-m-d H:i:s');
        $now->getTimestamp();
        $comment->setDate($now);

        $em->persist($comment);
        $em->flush();

        return new JsonResponse(["Status" => "Success"], Response::HTTP_ACCEPTED);
    }

    /**
     * @Route("/{id}", name="commentaire_show", methods={"GET"})
     */
    public function show(Request $request, CommentaireRepository $commentaireRepository): Response
    {
        $comments = $commentaireRepository->findBy(["id_produit" => $request->get("id")]);
        $data = $this->serializer->serialize($comments, "json", [AbstractNormalizer::IGNORED_ATTRIBUTES => ["users"]]);
        $data = json_decode($data);
        foreach ($comments as $key => $value) {
            $data[$key] = ["comment" => json_decode($this->serializer->serialize($value, "json", [AbstractNormalizer::IGNORED_ATTRIBUTES => ["users"]])), "email" => $value->getUsers()->getEmail()];
        }
        return new JsonResponse($data, Response::HTTP_ACCEPTED);
    }
}

e-commerce-symfony/templates/commentaire/_delete_form.html.twig
<form method="post" action="{{ path('commentaire_delete', {'id': commentaire.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commentaire.id) }}">
    <button class="btn">Delete</button>
</form>

e-commerce-symfony/templates/commentaire/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

e-commerce-symfony/templates/commentaire/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Commentaire{% endblock %}

{% block body %}
    <h1>Edit Commentaire</h1>

    {{ include('commentaire/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('commentaire_index') }}">back to list</a>

    {{ include('commentaire/_delete_form.html.twig') }}
{% endblock %}

e-commerce-symfony/templates/commentaire/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commentaire index{% endblock %}

{% block body %}
    <h1>Commentaire index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Id_produit</th>
                <th>Commentaire</th>
                <th>Date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for commentaire in commentaires %}
            <tr>
                <td>{{ commentaire.id }}</td>
                <td>{{ commentaire.idProduit }}</td>
                <td>{{ commentaire.commentaire }}</td>
                <td>{{ commentaire.date ? commentaire.date|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('commentaire_show', {'id': commentaire.id}) }}">show</a>
                    <a href="{{ path('commentaire_edit', {'id': commentaire.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('commentaire_new') }}">Create new</a>
{% endblock %}

e-commerce-symfony/templates/commentaire/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Commentaire{% endblock %}

{% block body %}
    <h1>Create new Commentaire</h1>

    {{ include('commentaire/_form.html.twig') }}

    <a href="{{ path('commentaire_index') }}">back to list</a>
{% endblock %}

e-commerce-symfony/templates/commentaire/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commentaire{% endblock %}

{% block body %}
    <h1>Commentaire</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ commentaire.id }}</td>
            </tr>
            <tr>
                <th>Id_produit</th>
                <td>{{ commentaire.idProduit }}</td>
            </tr>
            <tr>
                <th>Commentaire</th>
                <td>{{ commentaire.commentaire }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ commentaire.date ? commentaire.date|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('commentaire_index') }}">back to list</a>

    <a href="{{ path('commentaire_edit', {'id': commentaire.id}) }}">edit</a>

    {{ include('commentaire/_delete_form.html.twig') }}
{% endblock %}