e-commerce-symfony/src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Serializer\Annotation\Groups;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommandeRepository::class)
 */
class Commande
{
    /**
     * @Groups({"commande"})
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $montant;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_enregistrement;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $etat;

    /**
     * @Groups({"detail_commande"})
     * @ORM\OneToMany(targetEntity=DetailCommande::class, mappedBy="commande", orphanRemoval=true)
     */
    private $commande;

    /**
     * @Groups({"users"})
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="commande")
     * @ORM\JoinColumn(nullable=false)
     */
    private $users;

    public function __construct()
    {
        $this->commande = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMontant(): ?int
    {
        return $this->montant;
    }

    public function setMontant(int $montant): self
    {
        $this->montant = $montant;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): self
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(string $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    /**
     * @return Collection|DetailCommande[]
     */
    public function getCommande(): Collection
    {
        return $this->commande;
    }

    public function addCommande(DetailCommande $commande): self
    {
        if (!$this->commande->contains($commande)) {
            $this->commande[] = $commande;
            $commande->setCommande($this);
        }

        return $this;
    }

    public function removeCommande(DetailCommande $commande): self
    {
        if ($this->commande->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getCommande() === $this) {
                $commande->setCommande(null);
            }
        }

        return $this;
    }

    public function getUsers(): ?Users
    {
        return $this->users;
    }

    public function setUsers(?Users $users): self
    {
        $this->users = $users;

        return $this;
    }
}

e-commerce-symfony/src/Form/CommandeType.php
<?php

namespace App\Form;

use App\Entity\Commande;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommandeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('montant')
            ->add('date_enregistrement')
            ->add('etat')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Commande::class,
        ]);
    }
}

e-commerce-symfony/src/Controller/CommandeController.php
<?php

namespace App\Controller;

use Firebase\JWT\JWT;
use App\Entity\Product;
use App\Entity\Commande;
use App\Form\CommandeType;
use App\Entity\DetailCommande;
use App\Repository\UsersRepository;
use App\Repository\CommandeRepository;
use App\Repository\DetailCommandeRepository;
use App\Repository\ProductRepository;
use Symfony\Component\Serializer\Serializer;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Serializer\Encoder\XmlEncoder;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Normalizer\AbstractNormalizer;
use Symfony\Component\Serializer\Normalizer\DateTimeNormalizer;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\DependencyInjection\ParameterBag\ContainerBagInterface;

/**
 * @Route("/commande")
 */
class CommandeController extends AbstractController
{

    public function __construct(ContainerBagInterface $params)
    {
        $this->encoders = [new XmlEncoder(), new JsonEncoder()];
        $defaultContext = [
            AbstractNormalizer::CIRCULAR_REFERENCE_HANDLER => function ($object, $format, $context) {
                return $object->getId();
            },
        ];
        $this->normalizers = [new DateTimeNormalizer(), new ObjectNormalizer(null, null, null, null, null, null, $defaultContext)];
        $this->serializer = new Serializer($this->normalizers, $this->encoders);
        $this->params = $params;
    }

    /**
     * @Route("/", name="commande_index", methods={"GET"})
     */
    public function index(Request $request, UsersRepository $usersRepository, CommandeRepository $commandeRepository): Response
    {
        $credentials = $request->headers->get("Authorization");
        $jwt = (array) JWT::decode(
            $credentials,
            $this->params->get('jwt_secret'),
            ['HS256']
        );

        $user = $usersRepository->findOneBy(["email" => $jwt["user"]]);

        $commandes = $commandeRepository->findBy(["users" => $user]);

        $data = $this->serializer->serialize($commandes, 'json', ['groups' => ['commande'], AbstractNormalizer::IGNORED_ATTRIBUTES => ['users', 'commande']]);

        return new JsonResponse(json_decode($data), Response::HTTP_OK);
    }

    /**
     * @Route("/new", name="commande_new", methods={"GET","POST"})
     */
    public function new(Request $request, UsersRepository $usersRepository, CommandeRepository $commandeRepository, DetailCommandeRepository $detailCommandeRepository, ProductRepository $productRepository): Response
    {
        if ($request->get("quantity") === null || $request->get("quantity") <= 0) {
            return new JsonResponse(["Status" => "Error", "Msg" => "Invalid quantity"], Response::HTTP_BAD_REQUEST);
        }

        $em = $this->getDoctrine()->getManager();

        $credentials = $request->headers->get("Authorization");
        $jwt = (array) JWT::decode(
            $credentials,
            $this->params->get('jwt_secret'),
            ['HS256']
        );

        $user = $usersRepository->findOneBy(["email" => $jwt["user"]]);

        $panier = $commandeRepository->findOneBy(["users" => $user, "etat" => "Panier"]);

        // IF THERE IS NO CART FOR USER CREATE ONE 

        if (empty($panier)) {
            $newPanier = new Commande();
            $newPanier->setEtat("Panier");
            $newPanier->setUsers($user);
            $newPanier->setMontant(0);
            $now = new \DateTime();
            $now->format('Y-m-d H:i:s');
            $now->getTimestamp();
            $newPanier->setDateEnregistrement($now);
            $em->persist($newPanier);
            $em->flush();
            $panier = $commandeRepository->findOneBy(["users" => $user, "etat" => "Panier"]);
        }

        $produit = $productRepository->findOneBy(["id" => $request->get("id_produit")]);
        // INSERT PRODUCT INTO CART
        $dopple = $detailCommandeRepository->findOneBy(["id_produit" => $request->get("id_produit"), "commande" => $panier]);

        if ($dopple !== null) {
            $dopple->setQuantité($dopple->getQuantité() + $request->get("quantity"));
            $dopple->setPrix($produit->getPrice() * $dopple->getQuantité());
            $price = $request->get("quantity") * $produit->getPrice();
            $panier->setMontant($panier->getMontant() + $price);
            $em->persist($dopple);
            $em->flush();
            return new JsonResponse(["Status" => "Success", "Dopple" => true], Response::HTTP_ACCEPTED);
        }

        $newProduit = new DetailCommande();
        $newProduit->setIdProduit($request->get("id_produit"));
        $newProduit->setQuantité($request->get("quantity"));
        $newProduit->setPrix($produit->getPrice() * $newProduit->getQuantité());
        $newProduit->setCommande($panier);
        $panier->setMontant($panier->getMontant() + $newProduit->getPrix());
        $em->persist($newProduit);
        $em->flush();

        return new JsonResponse(["Status" => "Success", "Dopple" => false], Response::HTTP_ACCEPTED);
    }

    /**
     * @Route("/confirm", name="commande_confirm", methods={"POST"})
     */
    public function confirm(Request $request, UsersRepository $usersRepository, CommandeRepository $commandeRepository): Response
    {
        $em = $this->getDoctrine()->getManager();

        $credentials = $request->headers->get("Authorization");
        $jwt = (array) JWT::decode(
            $credentials,
            $this->params->get('jwt_secret'),
            ['HS256']
        );

        $user = $usersRepository->findOneBy(["email" => $jwt["user"]]);

        $commandes = $commandeRepository->findOneBy(["users" => $user, "etat" => "Panier"]);

        $commandes->setEtat("En cours de validation");

        $em->persist($commandes);
        $em->flush();

        return new JsonResponse(["Status" => "Success"], Response::HTTP_ACCEPTED);
    }
}

e-commerce-symfony/templates/commande/_delete_form.html.twig
<form method="post" action="{{ path('commande_delete', {'id': commande.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commande.id) }}">
    <button class="btn">Delete</button>
</form>

e-commerce-symfony/templates/commande/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

e-commerce-symfony/templates/commande/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Commande{% endblock %}

{% block body %}
    <h1>Edit Commande</h1>

    {{ include('commande/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('commande_index') }}">back to list</a>

    {{ include('commande/_delete_form.html.twig') }}
{% endblock %}

e-commerce-symfony/templates/commande/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande index{% endblock %}

{% block body %}
    <h1>Commande index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Montant</th>
                <th>Date_enregistrement</th>
                <th>Etat</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for commande in commandes %}
            <tr>
                <td>{{ commande.id }}</td>
                <td>{{ commande.montant }}</td>
                <td>{{ commande.dateEnregistrement ? commande.dateEnregistrement|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ commande.etat }}</td>
                <td>
                    <a href="{{ path('commande_show', {'id': commande.id}) }}">show</a>
                    <a href="{{ path('commande_edit', {'id': commande.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('commande_new') }}">Create new</a>
{% endblock %}

e-commerce-symfony/templates/commande/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Commande{% endblock %}

{% block body %}
    <h1>Create new Commande</h1>

    {{ include('commande/_form.html.twig') }}

    <a href="{{ path('commande_index') }}">back to list</a>
{% endblock %}

e-commerce-symfony/templates/commande/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande{% endblock %}

{% block body %}
    <h1>Commande</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ commande.id }}</td>
            </tr>
            <tr>
                <th>Montant</th>
                <td>{{ commande.montant }}</td>
            </tr>
            <tr>
                <th>Date_enregistrement</th>
                <td>{{ commande.dateEnregistrement ? commande.dateEnregistrement|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Etat</th>
                <td>{{ commande.etat }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('commande_index') }}">back to list</a>

    <a href="{{ path('commande_edit', {'id': commande.id}) }}">edit</a>

    {{ include('commande/_delete_form.html.twig') }}
{% endblock %}