e-commerce-symfony/src/Entity/CarteBancaire.php
<?php

namespace App\Entity;

use App\Repository\CarteBancaireRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CarteBancaireRepository::class)
 */
class CarteBancaire
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     */
    private $numCb;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $date_exp;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nomPrenom;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="cartebancaire")
     * @ORM\JoinColumn(nullable=false)
     */
    private $users;
    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumCb(): ?string
    {
        return $this->numCb;
    }

    public function setNumCb(int $numCb): self
    {
        $this->numCb = $numCb;

        return $this;
    }

    public function getDateExp(): ?string
    {
        return $this->date_exp;
    }

    public function setDateExp(string $date_exp): self
    {
        $this->date_exp = $date_exp;

        return $this;
    }

    public function getNomPrenom(): ?string
    {
        return $this->nomPrenom;
    }

    public function setNomPrenom(string $nomPrenom): self
    {
        $this->nomPrenom = $nomPrenom;

        return $this;
    }

    

    public function getUsers(): ?Users
    {
        return $this->users;
    }
    public function setUsers(?Users $users): self
    {
        $this->users = $users;
        return $this;
    }

   
}

e-commerce-symfony/src/Form/CarteBancaireType.php
<?php

namespace App\Form;

use App\Entity\CarteBancaire;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CarteBancaireType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('numCb')
            ->add('date_exp')
            ->add('nomPrenom')
            ->add('id_users')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => CarteBancaire::class,
        ]);
    }
}

e-commerce-symfony/src/Controller/CarteBancaireController.php
<?php

namespace App\Controller;

use Firebase\JWT\JWT;
use App\Entity\CarteBancaire;
use App\Form\CarteBancaireType;
use App\Repository\UsersRepository;
use App\Repository\CarteBancaireRepository;
use Symfony\Component\Serializer\Serializer;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Encoder\XmlEncoder;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Normalizer\AbstractNormalizer;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\DependencyInjection\ParameterBag\ContainerBagInterface;
use Symfony\Component\HttpFoundation\JsonResponse;

/**
 * @Route("/cb")
 */
class CarteBancaireController extends AbstractController
{
    

    public function __construct(ContainerBagInterface $params)
    {
        $this->encoders = [new XmlEncoder(), new JsonEncoder()];
        $defaultContext = [
            AbstractNormalizer::CIRCULAR_REFERENCE_HANDLER => function ($object, $format, $context) {
                return $object->getId();
            },
        ];
        $this->normalizers = [new ObjectNormalizer(null, null, null, null, null, null, $defaultContext)];
        $this->serializer = new Serializer($this->normalizers, $this->encoders);
        $this->params = $params;
    }

    /**
     * @Route("/", name="carte_bancaire_index", methods={"GET"})
     */

    public function index(CarteBancaireRepository $carteBancaireRepository, Request $request, UsersRepository $usersRepository): Response
    {
        $credentials = $request->headers->get("Authorization");
        $jwt = (array) JWT::decode(
            $credentials,
            $this->params->get('jwt_secret'),
            ['HS256']
        );
        $user = $usersRepository->findOneBy(["email" => $jwt["user"]]);
        $cb = $carteBancaireRepository->findBy(["users" => $user]);
        $data = $this->serializer->serialize($cb, 'json', [AbstractNormalizer::IGNORED_ATTRIBUTES => ['users']]);
        return new JsonResponse(json_decode($data), Response::HTTP_OK);
    }

    /**
     * @Route("/new", name="carte_bancaire_new", methods={"GET","POST"})
     */
    public function new(Request $request, UsersRepository $usersRepository, CarteBancaireRepository $carteBancaireRepository): Response
    {
        $num_cb = $request->get('num_cb');
        $date_exp = $request->get('date_exp');
        $nom_prenom = $request->get('nom_prenom');
        
        $credentials = $request->headers->get("Authorization");
        $jwt = (array) JWT::decode(
            $credentials,
            $this->params->get('jwt_secret'),
            ['HS256']
        );
        $user = $usersRepository->findOneBy(["email" => $jwt["user"]]);
        
        $cb = new CarteBancaire();
        $cb->setDateExp($date_exp);
        $cb->setNumCb($num_cb);
        $cb->setNomPrenom($nom_prenom);
        $cb->setUsers($user);

        
        $em = $this->getDoctrine()->getManager();
        
        $em->persist($cb);
        $em->flush();
        
        return $this->json([
        'status' => "sucess"
        ]);

    
        
        

        
    }

    /**
     * @Route("/{id}", name="carte_bancaire_show", methods={"GET"})
     */
    public function show(CarteBancaire $carteBancaire): Response
    {
        return $this->render('carte_bancaire/show.html.twig', [
            'carte_bancaire' => $carteBancaire,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="carte_bancaire_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, CarteBancaire $carteBancaire): Response
    {
        $form = $this->createForm(CarteBancaireType::class, $carteBancaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('carte_bancaire_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('carte_bancaire/edit.html.twig', [
            'carte_bancaire' => $carteBancaire,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/delete/{id}", name="carte_bancaire_delete", methods={"DELETE"})
     */
    public function delete(Request $request, CarteBancaireRepository $carteBancaireRepository ): Response
    {   
        $cb = $carteBancaireRepository->findOneBy(["id" => $request->get("id")]);
        
            $entityManager = $this->getDoctrine()->getManager();

            $entityManager->remove($cb);
            $entityManager->flush();
            return $this->json([
                'status' => "sucess"
                ]);
        

    }
}

e-commerce-symfony/templates/carte_bancaire/_delete_form.html.twig
<form method="post" action="{{ path('carte_bancaire_delete', {'id': carte_bancaire.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ carte_bancaire.id) }}">
    <button class="btn">Delete</button>
</form>

e-commerce-symfony/templates/carte_bancaire/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

e-commerce-symfony/templates/carte_bancaire/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit CarteBancaire{% endblock %}

{% block body %}
    <h1>Edit CarteBancaire</h1>

    {{ include('carte_bancaire/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('carte_bancaire_index') }}">back to list</a>

    {{ include('carte_bancaire/_delete_form.html.twig') }}
{% endblock %}

e-commerce-symfony/templates/carte_bancaire/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}CarteBancaire index{% endblock %}

{% block body %}
    <h1>CarteBancaire index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>NumCb</th>
                <th>Date_exp</th>
                <th>NomPrenom</th>
                <th>Id_users</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for carte_bancaire in carte_bancaires %}
            <tr>
                <td>{{ carte_bancaire.id }}</td>
                <td>{{ carte_bancaire.numCb }}</td>
                <td>{{ carte_bancaire.dateExp }}</td>
                <td>{{ carte_bancaire.nomPrenom }}</td>
                <td>{{ carte_bancaire.idUsers }}</td>
                <td>
                    <a href="{{ path('carte_bancaire_show', {'id': carte_bancaire.id}) }}">show</a>
                    <a href="{{ path('carte_bancaire_edit', {'id': carte_bancaire.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('carte_bancaire_new') }}">Create new</a>
{% endblock %}

e-commerce-symfony/templates/carte_bancaire/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New CarteBancaire{% endblock %}

{% block body %}
    <h1>Create new CarteBancaire</h1>

    {{ include('carte_bancaire/_form.html.twig') }}

    <a href="{{ path('carte_bancaire_index') }}">back to list</a>
{% endblock %}

e-commerce-symfony/templates/carte_bancaire/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}CarteBancaire{% endblock %}

{% block body %}
    <h1>CarteBancaire</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ carte_bancaire.id }}</td>
            </tr>
            <tr>
                <th>NumCb</th>
                <td>{{ carte_bancaire.numCb }}</td>
            </tr>
            <tr>
                <th>Date_exp</th>
                <td>{{ carte_bancaire.dateExp }}</td>
            </tr>
            <tr>
                <th>NomPrenom</th>
                <td>{{ carte_bancaire.nomPrenom }}</td>
            </tr>
            <tr>
                <th>Id_users</th>
                <td>{{ carte_bancaire.idUsers }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('carte_bancaire_index') }}">back to list</a>

    <a href="{{ path('carte_bancaire_edit', {'id': carte_bancaire.id}) }}">edit</a>

    {{ include('carte_bancaire/_delete_form.html.twig') }}
{% endblock %}